name: CI Pipeline

on:
  pull_request:
    branches:
      - master
      - cicd_settings
  push:
    branches:
      - master
      - cicd_settings
  workflow_dispatch:
    inputs:
      browser:
        description: 'Select browser for UI tests'
        required: true
        default: 'chrome'
        type: choice
        options:
          - chrome
          - firefox
          - edge
  schedule:
    - cron: '0 18 * * *'

jobs:
  tests:
    runs-on: windows-latest
    strategy:
      matrix:
        category: [API, UI]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Ensure directories for artifacts exist
        run: |
          if (!(Test-Path -Path "Screenshots")) {
            New-Item -ItemType Directory -Path "Screenshots"
          }
          if (!(Test-Path -Path "TestResults")) {
            New-Item -ItemType Directory -Path "TestResults"
          }

      - name: Run tests
        env:
          BROWSER: ${{ github.event.inputs.browser || 'chrome' }}
          CATEGORY: ${{ matrix.category }}
        run: |
          if ($env:CATEGORY -eq "UI") {
            Write-Host "Running UI tests with browser $env:BROWSER"
          }
          dotnet test --filter "Category=$env:CATEGORY" --logger "trx;LogFileName=TestResults/TestResults_$env:CATEGORY.trx"

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: TestResults/*.trx

      - name: Upload screenshots
        if: always() # Загружаем даже при провале тестов
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: Screenshots/*.png
