name: CI Pipeline

on:
  pull_request:
    branches:
      - master
      - cicd_settings
  push:
    branches:
      - master
      - cicd_settings
  workflow_dispatch:
    inputs:
      browser:
        description: 'Select browser for UI tests'
        required: true
        default: 'chrome'
        type: choice
        options:
          - chrome
          - firefox
          - edge
  schedule:
    - cron: '0 18 * * *'

jobs:
  tests:
    runs-on: windows-latest
    strategy:
      matrix:
        category: [API, UI]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Run tests
        env:
          BROWSER: ${{ github.event.inputs.browser || 'chrome' }}
          CATEGORY: ${{ matrix.category }}
        run: |
          if ($env:CATEGORY -eq "UI") {
            Write-Host "Running UI tests with browser $env:BROWSER"
          }
          dotnet test --filter "Category=$env:CATEGORY" --logger "trx;LogFileName=TestResults/TestResults_$env:CATEGORY.trx"

      - name: Upload screenshot if test fails
        if: failure()
        uses: actions/upload-artifact@v4.6.0
        with:
          name: screenshots
          path: ${{ github.workspace }}/ArtifactsFoulder/*.png

      - name: Upload screenshots
        if: failure()  # Выполняется, если тесты упали
        uses: actions/upload-artifact@v3
        with:
          name: failed-screenshots
          path: ./ArtifactsFoulder/*.png
